version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - github_actions

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - github_actions

  # maintain dependencies for python project
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - dependencies
    allow:
      # allow updates for specific clients
      - dependency-name: "Flask-APScheduler"
      - dependency-name: "PyYAML"
